export default [
    {data : [{v : 1,c : 1},{v : 122,c : 2},{v : 1,c : 1},{v : 1,c : 1},{v : 1,c : 1}],speed : 2},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : 1,c : 1},{v : 122,c : 2},{v : 1,c : 1},{v : -2, props : {s : 1}},{v : 1,c : 1}],speed : 2},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : -1, props : {c : 1}}],speed : 4},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : 0,},{v : -3, props : {p : 1}}],speed : 4},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : 0,},{v : -4,props : {w : 5}}],speed : 4},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
    {data : [{v : 0}]},
]